### ISSUE TITLE
pm2 save

### ISSUE THREAD

**Issue by pritha-intelliB** [weareinteractive/ansible-pm2#22]
hi,
After starting the app there we should be able to save the process .
pm2 save. what is the way I can achieve it here

**Comment by franklinkim** [comment]
hi, you could override the 'pm2_cmds' variabe and add your command...

**Comment by franklinkim** [comment]
mmh, just saw, that the pm2_cmds are veeing executed before handling the pm2_apps, so actually we would need pre and post commands... any PRs are welcome

**Comment by pritha-intelliB** [comment]
Hi,

just added the PR https://github.com/weareinteractive/ansible-pm2/pull/23

Thanks,
Pritha
